name: Chenyanglim
favicon: null
layout_spectrum: 0.01523
typography_spectrum: 0.8921
title: site title this is
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c6c3c4'
    - '#45434f'
    - '#918f9a'
    - '#e06a72'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
